"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, BookOpen, CalendarDays, FileText, LayoutDashboard, LogOut, Menu, RefreshCw, Search, Users, X } from "lucide-react";
import { getApiUrl } from "@/lib/utils";
import AppointmentActions from "@/app/doctor/appointments/AppointmentActions";

type Appointment = { id:string; name:string; email:string; phone?:string; date:string; time:string; reason:string; status:string; meeting_status?:string; videoRoom?:string; video_room?:string; consultation_status?:string; payment_status?:string; service_name?:string; consultation_fee?:number; patient_account_id?:string };
type Patient = { id:string; name:string; phone:string; age?:number; gender?:string; total_visits?:number; last_visit_date?:string };
type Blog = { id:string; title:string; slug:string; excerpt:string; content:string; cover_image?:string; category?:string; status:string; reading_time?:number; published_at?:string };
const nav=[["overview","Overview",LayoutDashboard],["appointments","Appointments",CalendarDays],["patients","Patients",Users],["followups","Follow-ups",Activity],["documents","Documents",FileText],["blogs","Blog Studio",BookOpen]] as const;
export default function DoctorDashboard(){
 const[token,setToken]=useState<string|null>(null),[login,setLogin]=useState({email:"",password:""}),[loginError,setLoginError]=useState(""),[active,setActive]=useState("overview"),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[appointments,setAppointments]=useState<Appointment[]>([]),[patients,setPatients]=useState<Patient[]>([]),[blogs,setBlogs]=useState<Blog[]>([]);
 const[blog,setBlog]=useState({title:"",excerpt:"",content:"",cover_image:"",category:"Health",status:"published",reading_time:5}),[editingId,setEditingId]=useState<string|null>(null);
 useEffect(()=>{const t=localStorage.getItem("doctorToken");if(t)setToken(t)},[]);
 const api=async(path:string,options:RequestInit={})=>{const r=await fetch(getApiUrl(path),{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d};
 const load=async()=>{if(!token)return;setLoading(true);try{const[a,p,b]=await Promise.all([api("/api/appointments"),api("/api/patients"),api("/api/doctor/blogs")]);setAppointments(a||[]);setPatients(p.patients||[]);setBlogs(b.blogs||[])}catch(e:any){setNotice(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[token]);
 const stats=useMemo(()=>({today:appointments.filter(a=>a.date===new Date().toISOString().slice(0,10)).length,confirmed:appointments.filter(a=>a.status==="Confirmed").length,active:appointments.filter(a=>a.meeting_status==="READY").length}),[appointments]);
 const doLogin=async(e:FormEvent)=>{e.preventDefault();setLoginError("");try{const r=await fetch(getApiUrl("/api/auth/login"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Invalid credentials");localStorage.setItem("doctorToken",d.token);setToken(d.token)}catch(e:any){setLoginError(e.message)}};
 const logout=()=>{localStorage.removeItem("doctorToken");setToken(null)};
 const updateAppointment=(updated:Appointment)=>setAppointments(v=>v.map(a=>a.id===updated.id?{...a,...updated}:a));
 const saveBlog=async(e:FormEvent)=>{e.preventDefault();try{const d=editingId?await api(`/api/doctor/blogs/${editingId}`,{method:"PUT",body:JSON.stringify(blog)}):await api("/api/doctor/blogs",{method:"POST",body:JSON.stringify(blog)});setNotice(editingId?"Article updated successfully":"Article published successfully");setEditingId(null);setBlog({title:"",excerpt:"",content:"",cover_image:"",category:"Health",status:"published",reading_time:5});setBlogs(v=>editingId?v.map(x=>x.id===d.blog.id?d.blog:x):[d.blog,...v]);setActive("blogs")}catch(e:any){setNotice(e.message)}};
 const editBlog=(b:Blog)=>{setEditingId(b.id);setBlog({title:b.title,excerpt:b.excerpt,content:b.content,cover_image:b.cover_image||"",category:b.category||"Health",status:b.status,reading_time:b.reading_time||5})};
 const deleteBlog=async(id:string)=>{if(!confirm("Delete this article?"))return;try{await api(`/api/doctor/blogs/${id}`,{method:"DELETE"});setBlogs(v=>v.filter(x=>x.id!==id));setNotice("Article deleted")}catch(e:any){setNotice(e.message)}};
 if(!token)return <main className="min-h-screen bg-[#f7f8f6] flex items-center justify-center p-6"><div className="w-full max-w-md bg-white rounded-[32px] border border-black/[0.06] shadow-xl p-9"><div className="w-12 h-12 rounded-2xl bg-[#1c251d] text-white flex items-center justify-center font-serif text-xl">H</div><h1 className="font-serif text-4xl text-[#1c251d] mt-6">Clinical Workspace</h1><p className="text-sm text-[#6b756c] mt-2">Dr. Varsha Bandi · Secure EMR</p><form onSubmit={doLogin} className="space-y-4 mt-8"><input data-testid="doctor-email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} type="email" placeholder="Doctor email" className="w-full rounded-2xl border border-black/10 px-4 py-3 text-sm" required/><input data-testid="doctor-password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} type="password" placeholder="Password" className="w-full rounded-2xl border border-black/10 px-4 py-3 text-sm" required/>{loginError&&<p className="text-xs text-red-600">{loginError}</p>}<button data-testid="doctor-login" className="w-full rounded-2xl bg-[#1c251d] text-white py-3.5 text-sm font-bold">Sign in</button></form></div></main>;
 return <main className="min-h-screen bg-[#f7f8f6] text-[#1c251d]"><aside className={`fixed z-40 inset-y-0 left-0 w-72 bg-white border-r border-black/[0.06] p-6 transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}><div className="flex justify-between items-center"><div><div className="font-serif text-xl font-semibold">Homeopathway</div><div className="text-[10px] uppercase tracking-[.2em] text-[#708264] mt-1">Clinical EMR</div></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div><nav className="mt-10 space-y-1">{nav.map(([id,label,Icon])=><button key={id} data-testid={`nav-${id}`} onClick={()=>{setActive(id);setMobile(false)}} className={`w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm font-semibold transition ${active===id?"bg-[#1c251d] text-white shadow-lg":"text-[#6b756c] hover:bg-[#f0f2ee]"}`}><Icon className="w-4 h-4"/>{label}</button>)}</nav><div className="absolute bottom-6 left-6 right-6 pt-5 border-t border-black/[0.06]"><div className="text-xs font-bold">Dr. Varsha Bandi</div><div className="text-[10px] text-[#6b756c] mt-1">HOD & Professor · 16+ years</div><button onClick={logout} className="mt-4 flex gap-2 items-center text-xs font-bold text-[#6b756c]"><LogOut className="w-3.5 h-3.5"/>Sign out</button></div></aside><section className="lg:ml-72 min-h-screen"><header className="sticky top-0 z-30 bg-[#f7f8f6]/90 backdrop-blur-xl border-b border-black/[0.05] px-5 lg:px-10 py-5 flex items-center justify-between"><div className="flex items-center gap-4"><button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div><div className="text-xs uppercase tracking-[.2em] text-[#708264] font-bold">Doctor Workspace</div><h1 className="font-serif text-2xl lg:text-3xl mt-1">{active==="blogs"?"Blog Studio":active[0].toUpperCase()+active.slice(1)}</h1></div></div><button onClick={load} className="p-2.5 rounded-xl bg-white border border-black/[0.06]" title="Refresh"><RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`}/></button></header><div className="p-5 lg:p-10 max-w-[1500px]">{notice&&<div className="mb-5 bg-white border border-black/[0.06] rounded-2xl px-5 py-3 text-sm flex justify-between"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
 {active==="overview"&&<><div className="grid md:grid-cols-4 gap-4">{[["Patients",patients.length,Users],["Today",stats.today,CalendarDays],["Confirmed",stats.confirmed,Activity],["Live",stats.active,Activity]].map(([label,value,Icon]:any)=><div key={label} className="bg-white rounded-3xl p-6 border border-black/[0.05]"><Icon className="w-5 h-5 text-[#708264]"/><div className="text-3xl font-semibold mt-5">{value}</div><div className="text-xs text-[#6b756c] mt-1">{label}</div></div>)}</div><div className="mt-7 bg-white rounded-3xl border border-black/[0.05] p-6"><div className="flex justify-between"><h2 className="font-serif text-2xl">New & upcoming appointments</h2><button onClick={()=>setActive("appointments")} className="text-xs font-bold text-[#708264]">View all</button></div><div className="mt-5 space-y-3">{appointments.slice(0,8).map(a=><div key={a.id} className="p-4 rounded-2xl bg-[#f7f8f6]"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="text-sm font-bold">{a.name}</div><div className="text-xs text-[#6b756c] mt-1">{a.service_name||"Homoeopathic Consultation"} · {a.date} · {a.time}</div></div><span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-white border">{a.status}</span></div><AppointmentActions appointment={a} onUpdated={updateAppointment} request={api}/></div>)}</div></div></>}
 {active==="appointments"&&<div className="space-y-4">{appointments.map(a=><article key={a.id} className="bg-white rounded-3xl border border-black/[0.05] p-6"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><div className="text-xs uppercase tracking-wider text-[#708264] font-bold">{a.service_name||"Homoeopathic Consultation"}</div><h2 className="font-serif text-3xl mt-1">{a.name}</h2><div className="text-xs text-[#6b756c] mt-2">{a.date} · {a.time} · {a.phone||"No phone"}</div><p className="text-sm text-[#59635b] mt-3">{a.reason}</p></div><div className="text-right"><div className="text-xs font-bold">₹{a.consultation_fee||800}</div><div className="text-[10px] text-[#6b756c] mt-1">Payment: {a.payment_status||"Unpaid"}</div></div></div><AppointmentActions appointment={a} onUpdated={updateAppointment} request={api}/></article>)}</div>}
 {active==="patients"&&<div className="bg-white rounded-3xl border border-black/[0.05] overflow-hidden"><div className="p-6 flex justify-between"><h2 className="font-serif text-2xl">Patient directory</h2><div className="flex items-center gap-2 border rounded-xl px-3"><Search className="w-4 h-4 text-[#6b756c]"/><input placeholder="Search" className="py-2 outline-none text-xs"/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#f7f8f6]"><tr><th className="p-4">Patient</th><th>Phone</th><th>Age</th><th>Gender</th><th>Visits</th></tr></thead><tbody>{patients.map(p=><tr key={p.id} className="border-t border-black/[0.04]"><td className="p-4 font-bold">{p.name}</td><td>{p.phone}</td><td>{p.age||"-"}</td><td>{p.gender||"-"}</td><td>{p.total_visits||0}</td></tr>)}</tbody></table></div></div>}
 {(active==="followups"||active==="documents")&&<div className="bg-white rounded-3xl border border-black/[0.05] p-10"><h2 className="font-serif text-3xl">{active==="followups"?"Follow-up workspace":"Document workspace"}</h2><p className="text-sm text-[#6b756c] mt-3">React workspace connected to the EMR API boundary.</p></div>}
 {active==="blogs"&&<div className="grid xl:grid-cols-[1.05fr_1fr] gap-6"><form onSubmit={saveBlog} className="bg-white rounded-3xl border border-black/[0.05] p-7 space-y-4"><h2 className="font-serif text-3xl">{editingId?"Edit article":"Publish article"}</h2><input data-testid="blog-title" value={blog.title} onChange={e=>setBlog({...blog,title:e.target.value})} placeholder="Article title" className="w-full border rounded-2xl px-4 py-3 text-sm" required/><input value={blog.excerpt} onChange={e=>setBlog({...blog,excerpt:e.target.value})} placeholder="Short excerpt" className="w-full border rounded-2xl px-4 py-3 text-sm"/><input value={blog.cover_image} onChange={e=>setBlog({...blog,cover_image:e.target.value})} placeholder="Cover image URL (optional)" className="w-full border rounded-2xl px-4 py-3 text-sm"/><textarea data-testid="blog-content" value={blog.content} onChange={e=>setBlog({...blog,content:e.target.value})} placeholder="Write the clinical article..." rows={13} className="w-full border rounded-2xl px-4 py-3 text-sm" required/><button className="w-full rounded-2xl bg-[#1c251d] text-white py-3.5 text-sm font-bold">{editingId?"Update article":"Publish article"}</button></form><div className="space-y-3">{blogs.map(b=><article key={b.id} className="bg-white rounded-3xl border border-black/[0.05] p-5"><div className="flex justify-between"><div><div className="text-xs font-bold text-[#708264]">{b.category||"Health"}</div><h3 className="font-serif text-2xl mt-1">{b.title}</h3></div><button onClick={()=>deleteBlog(b.id)} className="text-red-600 text-xs">Delete</button></div><button onClick={()=>editBlog(b)} className="mt-4 text-xs font-bold text-[#708264]">Edit</button></article>)}</div></div>}
 </div></section></main>;
}
