"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, BookOpen, CalendarDays, Check, FileText, LayoutDashboard, LogOut, Menu, MessageCircle, Play, RefreshCw, Search, Users, X } from "lucide-react";
import { getApiUrl } from "@/lib/utils";

type Appointment = {
  id: string; name: string; email: string; phone?: string; date: string; time: string;
  reason: string; status: string; meeting_status?: string; video_room?: string; videoRoom?: string;
  consultation_status?: string; payment_status?: string; service_name?: string; consultation_fee?: number;
};
type Patient = { id: string; name: string; phone: string; age?: number; gender?: string; total_visits?: number; last_visit_date?: string };
type Blog = { id: string; title: string; slug: string; excerpt?: string; content: string; cover_image?: string; category?: string; status: string; reading_time?: number; published_at?: string };
type Tab = "overview" | "appointments" | "patients" | "followups" | "documents" | "blogs";
const tabs: Array<[Tab, string, any]> = [["overview", "Overview", LayoutDashboard], ["appointments", "Appointments", CalendarDays], ["patients", "Patients", Users], ["followups", "Follow-ups", Activity], ["documents", "Documents", FileText], ["blogs", "Blog Studio", BookOpen]];

export default function DoctorDashboard() {
  const [token, setToken] = useState<string | null>(null), [login, setLogin] = useState({ email: "", password: "" }), [loginError, setLoginError] = useState("");
  const [active, setActive] = useState<Tab>("overview"), [mobile, setMobile] = useState(false), [loading, setLoading] = useState(false), [notice, setNotice] = useState(""), [search, setSearch] = useState("");
  const [appointments, setAppointments] = useState<Appointment[]>([]), [patients, setPatients] = useState<Patient[]>([]), [blogs, setBlogs] = useState<Blog[]>([]);
  const [blog, setBlog] = useState({ title: "", excerpt: "", content: "", cover_image: "", category: "Health", status: "published", reading_time: 5 }), [editingId, setEditingId] = useState<string | null>(null);

  useEffect(() => { const t = localStorage.getItem("doctorToken"); if (t) setToken(t); }, []);
  const api = async (path: string, options: RequestInit = {}) => { const r = await fetch(getApiUrl(path), { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "Request failed"); return d; };
  const load = async () => { if (!token) return; setLoading(true); setNotice(""); try { const [a, p, b] = await Promise.all([api("/api/doctor/appointments"), api("/api/patients"), api("/api/doctor/blogs")]); setAppointments(a.appointments || a || []); setPatients(p.patients || p || []); setBlogs(b.blogs || b || []); } catch (e: any) { setNotice(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [token]);

  const action = async (id: string, name: "accept" | "reject" | "confirm" | "start" | "complete") => { try { const result = await api(`/api/doctor/appointments/${id}/action`, { method: "POST", body: JSON.stringify({ action: name, roomName: `drvarsha-${id}` }) }); const saved = result.appointment || result; setAppointments(items => items.map(item => item.id === id ? saved : item)); setNotice(name === "start" ? "Consultation room is ready." : `Appointment ${name}d successfully.`); } catch (e: any) { setNotice(e.message); } };
  const openWhatsApp = (a: Appointment) => { if (!a.phone) return setNotice("This patient does not have a phone number."); const phone = a.phone.replace(/\D/g, ""); const message = `Hello ${a.name}, regarding your ${a.service_name || a.reason || "consultation"} with Dr. Varsha Bandi. Consultation fee: ₹${a.consultation_fee || "as discussed"}. Please complete the payment and share confirmation with the clinic.`; window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); };
  const logout = () => { localStorage.removeItem("doctorToken"); setToken(null); };
  const filteredPatients = useMemo(() => patients.filter(p => p.name.toLowerCase().includes(search.toLowerCase()) || (p.phone || "").includes(search)), [patients, search]);
  const stats = useMemo(() => ({ today: appointments.filter(a => a.date === new Date().toISOString().slice(0, 10)).length, pending: appointments.filter(a => ["Pending", "Accepted"].includes(a.status)).length, confirmed: appointments.filter(a => a.status === "Confirmed").length, live: appointments.filter(a => ["READY", "IN_PROGRESS"].includes(a.meeting_status || "")).length }), [appointments]);
  const saveBlog = async (e: FormEvent) => { e.preventDefault(); try { const d = editingId ? await api(`/api/doctor/blogs/${editingId}`, { method: "PUT", body: JSON.stringify(blog) }) : await api("/api/doctor/blogs", { method: "POST", body: JSON.stringify(blog) }); const saved = d.blog || d; setBlogs(items => editingId ? items.map(item => item.id === saved.id ? saved : item) : [saved, ...items]); setEditingId(null); setBlog({ title: "", excerpt: "", content: "", cover_image: "", category: "Health", status: "published", reading_time: 5 }); setNotice("Blog saved successfully."); } catch (e: any) { setNotice(e.message); } };

  if (!token) return <main className="min-h-screen bg-[#f7f8f6] flex items-center justify-center p-6"><div className="w-full max-w-md bg-white rounded-[32px] border border-black/[0.06] shadow-xl p-9"><div className="w-12 h-12 rounded-2xl bg-[#1c251d] text-white flex items-center justify-center font-serif text-xl">H</div><h1 className="font-serif text-4xl text-[#1c251d] mt-6">Clinical Workspace</h1><p className="text-sm text-[#6b756c] mt-2">Dr. Varsha Bandi · Secure EMR</p><form onSubmit={async e => { e.preventDefault(); try { const r = await fetch(getApiUrl("/api/auth/login"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(login) }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.error || "Invalid credentials"); localStorage.setItem("doctorToken", d.token); setToken(d.token); } catch (err: any) { setLoginError(err.message); } }} className="space-y-4 mt-8"><input data-testid="doctor-email" value={login.email} onChange={e => setLogin({ ...login, email: e.target.value })} type="email" placeholder="Doctor email" className="w-full rounded-2xl border px-4 py-3 text-sm" required /><input data-testid="doctor-password" value={login.password} onChange={e => setLogin({ ...login, password: e.target.value })} type="password" placeholder="Password" className="w-full rounded-2xl border px-4 py-3 text-sm" required />{loginError && <p className="text-xs text-red-600">{loginError}</p>}<button data-testid="doctor-login" className="w-full rounded-2xl bg-[#1c251d] text-white py-3.5 text-sm font-bold">Sign in</button></form></div></main>;

  return <main className="min-h-screen bg-[#f7f8f6] text-[#1c251d]"><aside className={`fixed z-40 inset-y-0 left-0 w-72 bg-white border-r border-black/[0.06] p-6 transition-transform lg:translate-x-0 ${mobile ? "translate-x-0" : "-translate-x-full"}`}><div className="flex justify-between items-center"><div><div className="font-serif text-xl font-semibold">Homeopathway</div><div className="text-[10px] uppercase tracking-[.2em] text-[#708264] mt-1">Clinical EMR</div></div><button className="lg:hidden" onClick={() => setMobile(false)}><X /></button></div><nav className="mt-10 space-y-1">{tabs.map(([id, label, Icon]) => <button key={id} data-testid={`nav-${id}`} onClick={() => { setActive(id); setMobile(false); }} className={`w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm font-semibold ${active === id ? "bg-[#1c251d] text-white shadow-lg" : "text-[#6b756c] hover:bg-[#f0f2ee]"}`}><Icon className="w-4 h-4" />{label}</button>)}</nav><div className="absolute bottom-6 left-6 right-6 pt-5 border-t border-black/[0.06]"><div className="text-xs font-bold">Dr. Varsha Bandi</div><div className="text-[10px] text-[#6b756c] mt-1">HOD & Professor · 16+ years</div><button onClick={logout} className="mt-4 flex gap-2 items-center text-xs font-bold text-[#6b756c]"><LogOut className="w-3.5 h-3.5" /> Sign out</button></div></aside><section className="lg:ml-72 min-h-screen"><header className="sticky top-0 z-30 bg-[#f7f8f6]/90 backdrop-blur-xl border-b px-5 lg:px-10 py-5 flex items-center justify-between"><div className="flex items-center gap-4"><button className="lg:hidden" onClick={() => setMobile(true)}><Menu /></button><div><div className="text-xs uppercase tracking-[.2em] text-[#708264] font-bold">Doctor Workspace</div><h1 className="font-serif text-2xl lg:text-3xl mt-1">{tabs.find(t => t[0] === active)?.[1]}</h1></div></div><button onClick={load} className="p-2.5 rounded-xl bg-white border" title="Refresh"><RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} /></button></div></header><div className="p-5 lg:p-10 max-w-[1500px]">{notice && <div className="mb-5 bg-white border rounded-2xl px-5 py-3 text-sm flex justify-between"><span>{notice}</span><button onClick={() => setNotice("")}><X className="w-4 h-4" /></button></div>}

  {active === "overview" && <><div className="grid md:grid-cols-4 gap-4">{[["Today", stats.today], ["Needs attention", stats.pending], ["Confirmed", stats.confirmed], ["Live rooms", stats.live]].map(([label, value]) => <div key={label} className="bg-white rounded-3xl p-6 border"><div className="text-3xl font-semibold">{value}</div><div className="text-xs text-[#6b756c] mt-1">{label}</div></div>)}</div><div className="mt-7 bg-white rounded-3xl border p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">Today&apos;s clinical schedule</h2><button onClick={() => setActive("appointments")} className="text-xs font-bold text-[#708264]">Open appointments</button></div><div className="mt-5 grid gap-3">{appointments.slice(0, 8).map(a => <div key={a.id} className="p-4 rounded-2xl bg-[#f7f8f6] flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="font-bold text-sm">{a.name}</div><div className="text-xs text-[#6b756c] mt-1">{a.date} · {a.time} · {a.service_name || a.reason}</div></div><span className="text-[10px] font-bold px-3 py-1.5 rounded-full bg-white border w-fit">{a.status}</span></div>)}</div></div></>}

  {active === "appointments" && <div className="space-y-4">{appointments.map(a => <article key={a.id} className="bg-white rounded-3xl border p-6 shadow-sm"><div className="flex flex-col xl:flex-row xl:items-start xl:justify-between gap-5"><div><div className="flex items-center gap-3"><h2 className="font-serif text-2xl">{a.name}</h2><span className="text-[10px] font-bold uppercase px-3 py-1 rounded-full bg-[#f3f4f0]">{a.status}</span></div><p className="text-xs text-[#6b756c] mt-2">{a.date} · {a.time} · {a.service_name || a.reason}</p><p className="text-xs mt-1">{a.phone || "No phone"} · {a.email}</p><p className="text-xs mt-2 font-semibold">Payment: {a.payment_status || "Unpaid"} · Meeting: {a.meeting_status || "PENDING"}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => action(a.id, "accept")} disabled={a.status !== "Pending"} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#edf5ec] disabled:opacity-40"><Check className="w-3.5 h-3.5 inline mr-1" />Accept</button><button onClick={() => action(a.id, "reject")} disabled={a.status !== "Pending"} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#fff0f0] text-red-700 disabled:opacity-40">Reject</button><button onClick={() => openWhatsApp(a)} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#edf7f2]"><MessageCircle className="w-3.5 h-3.5 inline mr-1" />WhatsApp</button><button onClick={() => action(a.id, "confirm")} disabled={!['Accepted','Paid','Payment Pending'].includes(a.status)} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#1c251d] text-white disabled:opacity-40">Confirm</button><button onClick={() => action(a.id, "start")} disabled={a.status !== "Confirmed"} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#e9eef5] disabled:opacity-40"><Play className="w-3.5 h-3.5 inline mr-1" />Join Video</button>{a.status === "In Progress" && <button onClick={() => action(a.id, "complete")} className="px-4 py-2.5 rounded-xl text-xs font-bold bg-[#f0f2ee]">Complete</button>}</div></div></article>)}</div>}

  {active === "patients" && <div className="bg-white rounded-3xl border overflow-hidden"><div className="p-6 flex flex-col md:flex-row gap-4 md:items-center md:justify-between"><h2 className="font-serif text-2xl">Patient directory</h2><div className="flex items-center gap-2 border rounded-xl px-3 bg-white"><Search className="w-4 h-4 text-[#6b756c]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search patient or phone" className="py-2 outline-none text-xs" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#f7f8f6]"><tr><th className="p-4">Patient</th><th>Phone</th><th>Age</th><th>Gender</th><th>Visits</th></tr></thead><tbody>{filteredPatients.map(p => <tr key={p.id} className="border-t"><td className="p-4 font-bold">{p.name}</td><td>{p.phone}</td><td>{p.age || "-"}</td><td>{p.gender || "-"}</td><td>{p.total_visits || 0}</td></tr>)}</tbody></table></div></div>}

  {active === "blogs" && <div className="grid xl:grid-cols-[1.05fr_1fr] gap-6"><form onSubmit={saveBlog} className="bg-white rounded-3xl border p-7 space-y-4"><h2 className="font-serif text-3xl">{editingId ? "Edit article" : "Publish article"}</h2><input data-testid="blog-title" value={blog.title} onChange={e => setBlog({ ...blog, title: e.target.value })} placeholder="Article title" className="w-full border rounded-2xl px-4 py-3 text-sm" required /><input value={blog.excerpt} onChange={e => setBlog({ ...blog, excerpt: e.target.value })} placeholder="Short excerpt" className="w-full border rounded-2xl px-4 py-3 text-sm" /><input value={blog.cover_image} onChange={e => setBlog({ ...blog, cover_image: e.target.value })} placeholder="Cover image URL" className="w-full border rounded-2xl px-4 py-3 text-sm" /><textarea data-testid="blog-content" value={blog.content} onChange={e => setBlog({ ...blog, content: e.target.value })} placeholder="Write the article..." rows={13} className="w-full border rounded-2xl px-4 py-3 text-sm" required /><div className="grid grid-cols-2 gap-3"><input value={blog.category} onChange={e => setBlog({ ...blog, category: e.target.value })} placeholder="Category" className="border rounded-2xl px-4 py-3 text-sm" /><select value={blog.status} onChange={e => setBlog({ ...blog, status: e.target.value })} className="border rounded-2xl px-4 py-3 text-sm"><option value="published">Publish now</option><option value="draft">Save draft</option></select></div><button data-testid="publish-blog" className="w-full bg-[#1c251d] text-white rounded-2xl py-3.5 text-sm font-bold">{editingId ? "Update article" : "Publish to website"}</button></form><div className="bg-white rounded-3xl border p-7"><h2 className="font-serif text-3xl">Articles</h2><div className="mt-5 space-y-3">{blogs.map(b => <div key={b.id} className="p-4 rounded-2xl bg-[#f7f8f6] flex items-center justify-between gap-4"><div><div className="font-bold text-sm">{b.title}</div><div className="text-[10px] text-[#6b756c] mt-1">{b.status} · /blogs/{b.slug}</div></div><button onClick={() => { setEditingId(b.id); setBlog({ title: b.title, excerpt: b.excerpt || "", content: b.content, cover_image: b.cover_image || "", category: b.category || "Health", status: b.status, reading_time: b.reading_time || 5 }); }} className="px-3 py-2 rounded-xl bg-white text-xs font-bold">Edit</button></div>)}</div></div></div>}

  {(active === "followups" || active === "documents") && <div className="bg-white rounded-3xl border p-8"><h2 className="font-serif text-3xl">{active === "followups" ? "Follow-up workspace" : "Document workspace"}</h2><p className="text-sm text-[#6b756c] mt-3">The React shell is ready, but these modules remain deliberately gated until their production API ownership contracts are verified. No clinical placeholder data is exposed.</p></div>}
  </div></section></main>;
}
